# Generated by Django 4.2.7 on 2023-12-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Completado', models.BooleanField(default=False)),
            ],
        ),
    ]
